[pytest]
addopts = --basetemp=.pytest_tmp -p no:cacheprovider
filterwarnings =
    ignore::DeprecationWarning:mlflow.*
    ignore::DeprecationWarning:pydantic.*
    ignore::DeprecationWarning:starlette.*
